# CI/CD to perform automated testing and deployment of code
# The workflow for code changes are as follows:
# - Changes are made in (or merged into) the development branch
# - The pipeline will then deploy the changes to the development server for testing
# - Once verified, merge the changes into the deploy branch
# - The pipeline will then deploy the changes to the production server
# - Once verified, merge the changes into the master branch (to be used by others)
#    The master branch does not have CI/CD in order to keep it as re-usable as possible

stages:
 - linting
 - unittest
 - deploy_dev
 - deploy_prod

variables:
  REPO_PATH: "/var/www/text-assembler/"
  CONNECT_DEVEL: "deploy@schanzme3.test.lib.msu.edu"
  CONNECT_PROD: "deploy@lexnex.lib.msu.edu"

linting_job:
 stage: linting
 tags:
  - msul
 only:
  - development
 script:
  - pip3 install -r requirements.txt
  - pylint3 --max-line-length=160 --load-plugins=pylint_django manage.py
  - pylint3 --max-line-length=160 --load-plugins=pylint_django textassembler_web
  - pylint3 --max-line-length=160 --load-plugins=pylint_django textassembler_processor
  - pylint3 --max-line-length=160 --load-plugins=pylint_django textassembler_web/templatetags/custom_tags.py
  - pylint3 --max-line-length=160 --load-plugins=pylint_django --disable=duplicate-code textassembler_processor/management/commands/*.py

unittest_job:
 stage: unittest
 tags:
  - msul
 only:
  - development
  - deploy
 script:
  - pip3 install -r requirements.txt
  - python3 manage.py test

deploy_dev_job:
  stage: deploy_dev
  tags:
    - msul
  only:
    - development
  script:
     - ssh $CONNECT_DEVEL git -C $REPO_PATH fetch origin development
     - ssh $CONNECT_DEVEL git -C $REPO_PATH checkout development
     - ssh $CONNECT_DEVEL git -C $REPO_PATH pull origin development
     - ssh $CONNECT_DEVEL /bin/bash -c '"cd $REPO_PATH && source ta_env/bin/activate && pip install -r requirements.txt && deactivate"'
     - ssh $CONNECT_DEVEL $REPO_PATH/ta_env/bin/python $REPO_PATH/manage.py migrate
     - ssh $CONNECT_DEVEL sudo systemctl restart apache2
     - ssh $CONNECT_DEVEL sudo systemctl restart tassemblerd
     - ssh $CONNECT_DEVEL sudo systemctl restart tassemblerzipd
     - ssh $CONNECT_DEVEL sudo systemctl restart tassemblerdeld
     
deploy_prod_job:
  stage: deploy_prod
  tags:
    - msul
  only:
    - deploy
  script:
     - ssh $CONNECT_PROD git -C $REPO_PATH fetch origin deploy
     - ssh $CONNECT_PROD git -C $REPO_PATH checkout deploy
     - ssh $CONNECT_PROD git -C $REPO_PATH pull origin deploy
     - ssh $CONNECT_PROD /bin/bash -c '"cd $REPO_PATH && source ta_env/bin/activate && pip install -r requirements.txt && deactivate"'
     - ssh $CONNECT_PROD $REPO_PATH/ta_env/bin/python $REPO_PATH/manage.py migrate
     - ssh $CONNECT_PROD sudo systemctl restart apache2
     - ssh $CONNECT_PROD sudo systemctl restart tassemblerd
     - ssh $CONNECT_PROD sudo systemctl restart tassemblerzipd
     - ssh $CONNECT_PROD sudo systemctl restart tassemblerdeld
