#!/bin/bash

sig_term() {
    kill -15 "$MANAGE_PID"
}

trap sig_term SIGINT SIGTERM

TASSEMBLERZIPD_LOG=/var/log/apache2/tassemblerzipd.log
SCRIPT_LOCATION="$( dirname "${BASH_SOURCE[0]}" )"
$SCRIPT_LOCATION/ta_env/bin/python $SCRIPT_LOCATION/manage.py compress_searches 1>> $TASSEMBLERZIPD_LOG 2>&1 &
MANAGE_PID=$!
wait $MANAGE_PID

