#!/bin/bash

sig_term() {
    kill -15 "$MANAGE_PID"
}

trap sig_term SIGINT SIGTERM

TEXTASSEMBLERD_LOG=/var/log/apache2/textassemblerd.log
SCRIPT_LOCATION="$( dirname "${BASH_SOURCE[0]}" )"
$SCRIPT_LOCATION/ta_env/bin/python $SCRIPT_LOCATION/manage.py process_queue 1>> $TEXTASSEMBLERD_LOG 2>&1 &
MANAGE_PID=$!
wait $MANAGE_PID

