# Generated by Django 2.2 on 2019-04-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textassembler_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='source_id',
            field=models.CharField(max_length=255),
        ),
    ]
