# Generated by Django 2.2 on 2019-05-06 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textassembler_web', '0002_auto_20190423_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='available_formats',
            fields=[
                ('format_id', models.AutoField(primary_key=True, serialize=False)),
                ('format_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='searches',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField()),
                ('query', models.TextField()),
                ('date_startd', models.DateTimeField()),
                ('date_completed', models.DateTimeField()),
                ('num_results_downloaded', models.IntegerField()),
                ('num_results_in_search', models.IntegerField()),
                ('skip_value', models.IntegerField()),
                ('date_started_compression', models.DateTimeField()),
                ('date_completed_compression', models.DateTimeField()),
                ('user_notified', models.BooleanField(default=False)),
                ('run_time_mins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=255)),
                ('filter_value', models.CharField(max_length=255)),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textassembler_web.searches')),
            ],
        ),
        migrations.CreateModel(
            name='download_formats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textassembler_web.available_formats')),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textassembler_web.searches')),
            ],
        ),
        migrations.RunSQL(
            """INSERT INTO textassembler_web_available_formats (format_name) 
            VALUES ('HTML'),('TXT'),('TXT Only');"""
        ),
    ]
