# Generated by Django 2.2 on 2019-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textassembler_web', '0003_available_formats_download_formats_filters_searches'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_formats',
            name='help_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.RunSQL("UPDATE textassembler_web_available_formats SET help_text = 'Original format from LexisNexis' WHERE format_name='HTML';"),
        migrations.RunSQL("UPDATE textassembler_web_available_formats SET help_text = 'Has the same contents of the HTML format but is saved as TXT' WHERE format_name='TXT';"),
        migrations.RunSQL("UPDATE textassembler_web_available_formats SET help_text = 'A TXT document containing only the article text, removing the metadata provided by the TXT and HTML formats' WHERE format_name='TXT Only';"),
    ]
