# Generated by Django 2.2 on 2019-05-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textassembler_web', '0005_auto_20190508_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='searches',
            name='errror_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='searches',
            name='failed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='searches',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='searches',
            name='num_results_downloaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='searches',
            name='num_results_in_search',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='searches',
            name='run_time_mins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='searches',
            name='skip_value',
            field=models.IntegerField(default=0),
        ),
    ]
