# Generated by Django 2.2 on 2019-05-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textassembler_web', '0006_auto_20190522_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searches',
            old_name='run_time_mins',
            new_name='run_time_seconds',
        ),
    ]
