# Generated by Django 2.2 on 2019-07-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textassembler_web', '0008_auto_20190611_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
