# Generated by Django 2.2 on 2019-07-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textassembler_web', '0009_sources_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='historical_searches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.IntegerField(default=0)),
                ('date_submitted', models.DateTimeField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('query', models.TextField()),
                ('date_started', models.DateTimeField(null=True)),
                ('date_completed', models.DateTimeField(null=True)),
                ('num_results_downloaded', models.IntegerField(default=0)),
                ('num_results_in_search', models.IntegerField(default=0)),
                ('skip_value', models.IntegerField(default=0)),
                ('date_started_compression', models.DateTimeField(null=True)),
                ('date_completed_compression', models.DateTimeField(null=True)),
                ('user_notified', models.BooleanField(default=False)),
                ('run_time_seconds', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(null=True)),
                ('failed_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
