# Generated by Django 2.2 on 2019-07-08 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('textassembler_web', '0010_historical_searches'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_searches',
            name='date_deleted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
