# Generated by Django 2.2 on 2019-08-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textassembler_web', '0011_historical_searches_date_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_searches',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searches',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
