# Generated by Django 2.2 on 2019-08-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textassembler_web', '0013_auto_20190802_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
            ],
        ),
    ]
