# Generated by Django 2.2.5 on 2019-09-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textassembler_web', '0016_api_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='searches',
            name='last_save_dir',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
