# Generated by Django 2.2.5 on 2019-12-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textassembler_web', '0018_auto_20191004_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_limits',
            old_name='per_day',
            new_name='limit_per_day',
        ),
        migrations.RenameField(
            model_name='api_limits',
            old_name='per_hour',
            new_name='limit_per_hour',
        ),
        migrations.RenameField(
            model_name='api_limits',
            old_name='per_minute',
            new_name='limit_per_minute',
        ),
        migrations.AddField(
            model_name='api_limits',
            name='remaining_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api_limits',
            name='remaining_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api_limits',
            name='remaining_per_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api_limits',
            name='reset_on_day',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='api_limits',
            name='reset_on_hour',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='api_limits',
            name='reset_on_minute',
            field=models.DateTimeField(null=True),
        ),
    ]
