# Generated by Django 2.2 on 2019-04-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_url', models.CharField(max_length=500)),
                ('request_type', models.CharField(max_length=10)),
                ('response_code', models.CharField(max_length=10)),
                ('num_results', models.IntegerField()),
                ('is_download', models.BooleanField()),
                ('request_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='limits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searches_per_minute', models.IntegerField()),
                ('searches_per_hour', models.IntegerField()),
                ('searches_per_day', models.IntegerField()),
                ('downloads_per_minute', models.IntegerField()),
                ('downloads_per_hour', models.IntegerField()),
                ('downloads_per_day', models.IntegerField()),
                ('weekday_start_time', models.TimeField()),
                ('weekday_end_time', models.TimeField()),
                ('weekend_start_time', models.TimeField()),
                ('weekend_end_time', models.TimeField()),
            ],
        ),
        migrations.RunSQL("""
            INSERT INTO textassembler_processor_limits (searches_per_minute, searches_per_hour,
                searches_per_day, downloads_per_minute, downloads_per_hour, downloads_per_day,
                weekday_start_time, weekday_end_time, weekend_start_time, weekend_end_time)
                VALUES
                (5,100,100,
                5,100,100,
                '23:00', '06:00', '00:00','00:00');
            """),
    ]
