# Generated by Django 2.2 on 2019-06-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textassembler_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_log',
            name='request_url',
            field=models.TextField(),
        ),
    ]
