# Generated by Django 2.2 on 2019-07-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textassembler_processor', '0002_auto_20190628_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='limits',
        ),
    ]
